/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CrashesRouteImport } from './routes/crashes'
import { Route as DataRouteImport } from './routes/data'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SensitivityRouteImport } from './routes/sensitivity'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiPublicMarketLatestRouteImport } from './routes/api/public/market-latest'
import { Route as ApiPublicQuotesRouteImport } from './routes/api/public/quotes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashesRoute = CrashesRouteImport.update({
  id: '/crashes',
  path: '/crashes',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitivityRoute = SensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketLatestRoute = ApiPublicMarketLatestRouteImport.update({
  id: '/api/public/market-latest',
  path: '/api/public/market-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuotesRoute = ApiPublicQuotesRouteImport.update({
  id: '/api/public/quotes',
  path: '/api/public/quotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/crashes': typeof CrashesRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensitivity': typeof SensitivityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/market-latest': typeof ApiPublicMarketLatestRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/crashes': typeof CrashesRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensitivity': typeof SensitivityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/market-latest': typeof ApiPublicMarketLatestRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/compare': typeof CompareRoute
  '/crashes': typeof CrashesRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensitivity': typeof SensitivityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/market-latest': typeof ApiPublicMarketLatestRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/crashes'
    | '/data'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/records'
    | '/reset-password'
    | '/sensitivity'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/api/public/market-latest'
    | '/api/public/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/crashes'
    | '/data'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/records'
    | '/reset-password'
    | '/sensitivity'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/api/public/market-latest'
    | '/api/public/quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/compare'
    | '/crashes'
    | '/data'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/records'
    | '/reset-password'
    | '/sensitivity'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/api/public/market-latest'
    | '/api/public/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRoute
  CompareRoute: typeof CompareRoute
  CrashesRoute: typeof CrashesRoute
  DataRoute: typeof DataRoute
  ForecastRoute: typeof ForecastRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  RecordsRoute: typeof RecordsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SensitivityRoute: typeof SensitivityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiPublicMarketLatestRoute: typeof ApiPublicMarketLatestRoute
  ApiPublicQuotesRoute: typeof ApiPublicQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crashes': {
      id: '/crashes'
      path: '/crashes'
      fullPath: '/crashes'
      preLoaderRoute: typeof CrashesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitivity': {
      id: '/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof SensitivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-latest': {
      id: '/api/public/market-latest'
      path: '/api/public/market-latest'
      fullPath: '/api/public/market-latest'
      preLoaderRoute: typeof ApiPublicMarketLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quotes': {
      id: '/api/public/quotes'
      path: '/api/public/quotes'
      fullPath: '/api/public/quotes'
      preLoaderRoute: typeof ApiPublicQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRoute,
  CompareRoute: CompareRoute,
  CrashesRoute: CrashesRoute,
  DataRoute: DataRoute,
  ForecastRoute: ForecastRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  RecordsRoute: RecordsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SensitivityRoute: SensitivityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  ApiPublicMarketLatestRoute: ApiPublicMarketLatestRoute,
  ApiPublicQuotesRoute: ApiPublicQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
